#repos:
#  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
#    rev: v2.4.0
#    hooks:
#      - id: check-ast
#      - id: end-of-file-fixer
#  - repo: 'https://github.com/psf/black'
#    rev: 22.3.0
#    hooks:
#      - id: black
#        args: [--config=./pyproject.toml]
#default_language_version:
#    python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.5.0"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer


  - repo: local

    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        args: [ --line-length=200, --target-version=py311 ]

      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [ python ]
        args: [ --in-place, --remove-all-unused-imports, --remove-duplicate-keys ]



      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: system
        types: [ python ]
        args: [ --py311-plus ]

      - id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: system
        types: [ python ]
        args: [ --py311-plus ]

      - id: yesqa
        name: yesqa
        entry: yesqa
        language: system
        types: [ python ]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        'types_or': [python, pyi]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
#      - id: tests
#        name: Run tests
#        entry: "bash test.sh"
#        language: system
#        verbose: true
